"""Ajustes cliente de novo

Revision ID: 095f985ee628
Revises: 80456f5aaa78
Create Date: 2020-07-02 10:53:59.749849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095f985ee628'
down_revision = '80456f5aaa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clientes_cnpj_cpf'), 'clientes', ['cnpj_cpf'], unique=True)
    op.drop_constraint('clientes_cnpj_cpf_key', 'clientes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('clientes_cnpj_cpf_key', 'clientes', ['cnpj_cpf'])
    op.drop_index(op.f('ix_clientes_cnpj_cpf'), table_name='clientes')
    # ### end Alembic commands ###
