"""empty message

Revision ID: 1d4ed089d31f
Revises: b49932075c64
Create Date: 2020-06-03 15:57:05.435138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4ed089d31f'
down_revision = 'b49932075c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pedidos_clientes', 'pedidos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_pedidos_clientes', 'pedidos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
