"""nova migracao

Revision ID: 246fea94edc8
Revises: 
Create Date: 2020-04-16 16:22:44.651353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246fea94edc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op', sa.Integer(), nullable=True),
    sa.Column('maquina', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.String(length=75), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('item', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('d_int', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=65), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('gramatura', sa.Float(), nullable=True),
    sa.Column('comprimento', sa.Float(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.Column('data_embarque', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.Column('tp_usuario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_login'), 'usuarios', ['login'], unique=True)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_login'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
