"""tabela Cliente

Revision ID: 29ee32c46e3f
Revises: 44be5968a863
Create Date: 2020-06-03 13:43:45.051073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee32c46e3f'
down_revision = '44be5968a863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_maquina', sa.Integer(), nullable=True),
    sa.Column('maquina', sa.String(length=75), nullable=True),
    sa.Column('pistas', sa.Integer(), nullable=True),
    sa.Column('largura_minima', sa.Integer(), nullable=True),
    sa.Column('largura_maxima', sa.Integer(), nullable=True),
    sa.Column('polegadas', sa.Integer(), nullable=True),
    sa.Column('transparente', sa.Boolean(), nullable=True),
    sa.Column('metalizado', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_material', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=75), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('maquinas')
    op.add_column('clientes', sa.Column('nome', sa.String(length=75), nullable=True))
    op.add_column('clientes', sa.Column('segmento', sa.String(length=75), nullable=True))
    op.add_column('clientes', sa.Column('situacao_do_cliente', sa.Integer(), nullable=True))
    op.drop_column('clientes', 'contato')
    op.drop_column('clientes', 'cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('cliente', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('contato', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('clientes', 'situacao_do_cliente')
    op.drop_column('clientes', 'segmento')
    op.drop_column('clientes', 'nome')
    op.create_table('maquinas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('maquina', sa.VARCHAR(length=75), autoincrement=False, nullable=True),
    sa.Column('quantidade_pistas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tamanho_minimo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tamanho_maximo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('polegadas_corte', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filme_transparente', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('metalizado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='maquinas_pkey')
    )
    op.drop_table('material')
    op.drop_table('maquina')
    # ### end Alembic commands ###
