"""Ajustes cliente

Revision ID: 4109dc7aa72a
Revises: 6083295b1dc7
Create Date: 2020-07-02 11:54:35.325826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4109dc7aa72a'
down_revision = '6083295b1dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividade', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atividade', 'clientes', ['cliente_id'], ['id'])
    op.add_column('pedidos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'cliente_id')
    op.drop_constraint(None, 'atividade', type_='foreignkey')
    op.drop_column('atividade', 'cliente_id')
    # ### end Alembic commands ###
