"""empty message

Revision ID: 44be5968a863
Revises: a6a2e3ad289f
Create Date: 2020-05-21 13:00:21.515537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44be5968a863'
down_revision = 'a6a2e3ad289f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina', sa.String(length=75), nullable=True),
    sa.Column('quantidade_pistas', sa.Integer(), nullable=True),
    sa.Column('tamanho_minimo', sa.Integer(), nullable=True),
    sa.Column('tamanho_maximo', sa.Integer(), nullable=True),
    sa.Column('polegadas_corte', sa.Integer(), nullable=True),
    sa.Column('filme_transparente', sa.Boolean(), nullable=True),
    sa.Column('metalizado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maquinas')
    # ### end Alembic commands ###
