"""Ajustes cliente

Revision ID: 6083295b1dc7
Revises: 095f985ee628
Create Date: 2020-07-02 11:53:12.249858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6083295b1dc7'
down_revision = '095f985ee628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('atividade_cliente_id_fkey', 'atividade', type_='foreignkey')
    op.drop_column('atividade', 'cliente_id')
    op.drop_constraint('pedidos_cliente_id_fkey', 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'cliente_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pedidos_cliente_id_fkey', 'pedidos', 'clientes', ['cliente_id'], ['id'])
    op.add_column('atividade', sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('atividade_cliente_id_fkey', 'atividade', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
