"""Fk codigo na Atividade

Revision ID: 7bce4cd42812
Revises: 90c64948eafd
Create Date: 2020-07-10 10:50:13.763433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bce4cd42812'
down_revision = '90c64948eafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('atividade_cliente_id_fkey', 'atividade', type_='foreignkey')
    op.create_foreign_key(None, 'atividade', 'clientes', ['cliente_id'], ['codigo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atividade', type_='foreignkey')
    op.create_foreign_key('atividade_cliente_id_fkey', 'atividade', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###
