"""Atividadehist e acoes

Revision ID: 80456f5aaa78
Revises: 811a4f366a1e
Create Date: 2020-07-01 11:29:04.904591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80456f5aaa78'
down_revision = '811a4f366a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('is_ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('is_ativa', sa.Boolean(), nullable=True),
    sa.Column('acao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['acao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividadeHistorico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('acao_id', sa.Integer(), nullable=True),
    sa.Column('subacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['acao.id'], ),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], ),
    sa.ForeignKeyConstraint(['subacao_id'], ['subacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atividadeHistorico')
    op.drop_table('subacao')
    op.drop_table('acao')
    # ### end Alembic commands ###
