"""clientes e atividades

Revision ID: 811a4f366a1e
Revises: defe3f1ea9cc
Create Date: 2020-07-01 10:54:27.023354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811a4f366a1e'
down_revision = 'defe3f1ea9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clientes', sa.Column('cnpj_cpf', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('codigo', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('e_mail', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('fone', sa.String(length=11), nullable=True))
    op.add_column('clientes', sa.Column('nome_fantasia', sa.String(length=75), nullable=True))
    op.add_column('clientes', sa.Column('porte', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('segmento_descricao', sa.String(length=75), nullable=True))
    op.add_column('clientes', sa.Column('segmento_mercado', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('subsegmento_descricao', sa.String(length=75), nullable=True))
    op.add_column('clientes', sa.Column('subsegmento_mercado', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('tipo_cliente', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('tipo_vinculo', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'clientes', ['cnpj_cpf'])
    op.drop_column('clientes', 'segmento')
    op.drop_column('clientes', 'situacao_do_cliente')
    op.drop_column('clientes', 'telefone')
    op.drop_column('pedidos', 'cliente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('cliente', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('telefone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('situacao_do_cliente', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('clientes', sa.Column('segmento', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_column('clientes', 'tipo_vinculo')
    op.drop_column('clientes', 'tipo_cliente')
    op.drop_column('clientes', 'subsegmento_mercado')
    op.drop_column('clientes', 'subsegmento_descricao')
    op.drop_column('clientes', 'segmento_mercado')
    op.drop_column('clientes', 'segmento_descricao')
    op.drop_column('clientes', 'porte')
    op.drop_column('clientes', 'nome_fantasia')
    op.drop_column('clientes', 'fone')
    op.drop_column('clientes', 'e_mail')
    op.drop_column('clientes', 'codigo')
    op.drop_column('clientes', 'cnpj_cpf')
    op.drop_table('atividade')
    # ### end Alembic commands ###
