"""Fk change

Revision ID: 8428a8e7c9ed
Revises: ebf0dd0ce693
Create Date: 2020-07-10 09:30:37.521608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8428a8e7c9ed'
down_revision = 'ebf0dd0ce693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clientes', ['codigo'])
    op.drop_constraint('pedidos_cliente_id_fkey', 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['codigo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key('pedidos_cliente_id_fkey', 'pedidos', 'clientes', ['cliente_id'], ['id'])
    op.drop_constraint(None, 'clientes', type_='unique')
    # ### end Alembic commands ###
