"""Tabela motivoAcao

Revision ID: 90c64948eafd
Revises: 8428a8e7c9ed
Create Date: 2020-07-10 10:22:36.578787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c64948eafd'
down_revision = '8428a8e7c9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividadeHistorico', sa.Column('motivoAcao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'atividadeHistorico', 'motivoacao', ['motivoAcao_id'], ['id'])
    op.drop_column('atividadeHistorico', 'motivoacao_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividadeHistorico', sa.Column('motivoacao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'atividadeHistorico', type_='foreignkey')
    op.drop_column('atividadeHistorico', 'motivoAcao_id')
    # ### end Alembic commands ###
