"""nome nao unico

Revision ID: a10ce7a7dd95
Revises: aaae46171653
Create Date: 2020-08-14 12:14:14.794318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10ce7a7dd95'
down_revision = 'aaae46171653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuarios_nome', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.create_index('ix_usuarios_nome', 'usuarios', ['nome'], unique=True)
    # ### end Alembic commands ###
