"""coluna cod_barra em estoque

Revision ID: a6a2e3ad289f
Revises: d4c9d41141e5
Create Date: 2020-04-24 09:53:02.194587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a2e3ad289f'
down_revision = 'd4c9d41141e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('cod_barra', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoque', 'cod_barra')
    # ### end Alembic commands ###
