"""col situacao in pedido

Revision ID: aaae46171653
Revises: 04483cf3b8b6
Create Date: 2020-07-22 09:46:19.234606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaae46171653'
down_revision = '04483cf3b8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimitem')
    op.add_column('pedidos', sa.Column('situacao', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'situacao')
    op.create_table('dimitem',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cod_item', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao_item', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('referencia', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cod_grupo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao_grupo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cod_subgrupo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descricao_subgrupo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_dimitem')
    )
    # ### end Alembic commands ###
