"""atualização

Revision ID: b49932075c64
Revises: 29ee32c46e3f
Create Date: 2020-06-03 15:36:53.298401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49932075c64'
down_revision = '29ee32c46e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('cliente_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'cliente_id')
    # ### end Alembic commands ###
