"""tabela estoque

Revision ID: d4c9d41141e5
Revises: 246fea94edc8
Create Date: 2020-04-17 09:17:07.983427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c9d41141e5'
down_revision = '246fea94edc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_item', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=True),
    sa.Column('largura', sa.Float(), nullable=True),
    sa.Column('item', sa.String(length=75), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('metros', sa.Float(), nullable=True),
    sa.Column('endereco', sa.String(length=75), nullable=True),
    sa.Column('area', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque')
    # ### end Alembic commands ###
