"""empty message

Revision ID: defe3f1ea9cc
Revises: 1d4ed089d31f
Create Date: 2020-06-03 15:58:45.219330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defe3f1ea9cc'
down_revision = '1d4ed089d31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'pedidos', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.alter_column('pedidos', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
