"""is_finalizada na Atividade

Revision ID: dff043b26ab9
Revises: 7bce4cd42812
Create Date: 2020-07-10 15:29:35.672036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff043b26ab9'
down_revision = '7bce4cd42812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividadeHistorico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.Column('acao_id', sa.Integer(), nullable=True),
    sa.Column('subacao_id', sa.Integer(), nullable=True),
    sa.Column('motivoAcao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['acao.id'], ),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], ),
    sa.ForeignKeyConstraint(['motivoAcao_id'], ['motivoacao.id'], ),
    sa.ForeignKeyConstraint(['subacao_id'], ['subacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('atividadehistorico')
    op.add_column('atividade', sa.Column('is_finalizada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atividade', 'is_finalizada')
    op.create_table('atividadehistorico',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"atividadeHistorico_id_seq"\'::regclass)'), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('atividade_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subacao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivoacao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acao_id'], ['acao.id'], name='atividadeHistorico_acao_id_fkey'),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividade.id'], name='atividadeHistorico_atividade_id_fkey'),
    sa.ForeignKeyConstraint(['motivoacao_id'], ['motivoacao.id'], name='atividadeHistorico_motivoAcao_id_fkey'),
    sa.ForeignKeyConstraint(['subacao_id'], ['subacao.id'], name='atividadeHistorico_subacao_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='atividadeHistorico_pkey')
    )
    op.drop_table('atividadeHistorico')
    # ### end Alembic commands ###
