"""Nao unique email

Revision ID: e3784d4aadca
Revises: a10ce7a7dd95
Create Date: 2020-08-14 22:55:10.619947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3784d4aadca'
down_revision = 'a10ce7a7dd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###
