"""empty message

Revision ID: ebf0dd0ce693
Revises: 4109dc7aa72a
Create Date: 2020-07-10 09:26:17.042192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf0dd0ce693'
down_revision = '4109dc7aa72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motivoacao')
    op.drop_column('atividadeHistorico', 'motivoacao_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atividadeHistorico', sa.Column('motivoacao_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('motivoacao',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_ativa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='motivoacao_pkey')
    )
    # ### end Alembic commands ###
